### ISSUE TITLE
Add support for Unified Compaction Strategy (UCS)

### ISSUE THREAD

**Issue by george0st** [rustyrazorblade/easy-cass-stress#30]
It will be useful to add support for Unified Compaction Strategy (UCS), see news in Cassandra v5.

**Comment by rustyrazorblade** [comment]
There's nothing special needed to use different compaction strategies.  You can pass in your configuration for UCS to the `--compaction` flag and it'll just work. 

You can also use the UCS shorthand:

`--compaction ucs,L4,L10` where the parameters that come after ucs are scaling parameters.

**Comment by george0st** [comment]
Add #31
